name: Python package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
        
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv PyKaldi_env
        # python -m pip install flake8 pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        PyKaldi_env/bin/python3 -m pip install numpy pyparsing ninja
        # Kaldi dependencies
        sudo apt-get install sox
        export py_env=$PWD/PyKaldi_env
    - name: check PWD
      run: |
        ls -la
        pwd
        cd ~
        pwd
    - name: Check Venv
      run: |
        source PyKaldi_env/bin/activate
        python -m pip -V
    - name: Check Venv
      run: |
          python3 -m pip -V
          pip -V
    - name: Check dependencies
      run: |
        cd tools
        ./tools/check_dependencies.sh
    - name: Build protobuf
      run: |
        cd tools
        ./install_protobuf.sh ../PyKaldi_env/bin/python3
    - name: Build clif
      run: |
        cd tools
        ./install_clif.sh ../PyKaldi_env/bin/python3
    - name: Build kaldi
      run: |
        cd tools
        git clone -b pykaldi_02 https://github.com/pykaldi/kaldi.git
        cd kaldi/tools
        git pull
        cd extras
        sudo ./install_mkl.sh
        cd ../../..
        ./install_kaldi.sh ../PyKaldi_env/bin/python3
    - name: Build PyKaldi
      run: |
        PyKaldi_env/bin/python3 setup.py install
    - name: Test PyKaldi
      run: |
        PyKaldi_env/bin/python3 setup.py test
    - name: Create Wheel
      run: |
        PyKaldi_env/bin/python3 setup.py sdist bdist_wheel
        cd dist
        ls -l
