name: Upload PyKaldi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
        
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv
        python -m virtualenv pykaldi_env
        # python -m pip install flake8 pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pykaldi_env/bin/python3 -m pip install numpy pyparsing ninja wheel
        # Kaldi dependencies
        sudo apt-get install sox
        git config --global http.version HTTP/1.1
    - name: Check dependencies
      run: |
        source pykaldi_env/bin/activate
        cd tools
        ./check_dependencies.sh
    - name: Build protobuf
      run: |
        source pykaldi_env/bin/activate
        cd tools
        ./install_protobuf.sh
    - name: Pushes test file
      uses:  dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'extras/'
        destination_repo: 'alienmaster/pykaldi'
        destination_folder: 'docker'
        user_email: 'mitachundkrach@gmail.com'
        user_name: 'Alienmaster'
        destination_branch: 'master'
